---
title: "celltype_annotations"
author: "heinin"
date: "2023-12-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Cell type annotations for spatial data.

### Packages and environment variables

```{r}

suppressPackageStartupMessages({library(cli)
                                library(Seurat)
                                library(SeuratObject)
                                library(SeuratDisk)
                                library(tidyverse)
                                library(tibble)
                                library(ggplot2)
                                library(ggpubr)
                                library(ggrepel)
                                library(workflowr)})

setwd("/home/hnatri/ILD_ASE_Xenium/")
set.seed(9999)
options(ggrepel.max.overlaps = Inf)

# Colors, themes, cell type markers, and plot functions
source("/home/hnatri/ILD_ASE_Xenium/code/colors_themes.R")
source("/home/hnatri/ILD_ASE_Xenium/code/plot_functions.R")

```

### Cell type markers

```{r}
epithelial_features <- c("EGFR", "DUOX1", "NKX2-1", "AGER", "RTKN2", "NAPSA",
                         "PGC", "SFTA2", "SFTPC", "SFTPD", "KRT14", "KRT15",
                         "KRT5", "KRT6A", "S100A2", "TP63", "KRT17", "AGR3",
                         "C20orf85", "FOXJ1", "GCLM", "DMBT1", "EPCAM", "KRT18",
                         "MGST1", "MMP7", "FOXI1", "MUC5B", "SCGB1A1",
                         "SCGB3A2", "WFDC2", "ATF3", "KRT8", "SOX9", "SPINK1",
                         "GKN2", "MMP10", "SOX2", "CDH26", "TP73", "CFTR",
                         "HES1", "PKM", "SOX4", "NUCB2", "RNASE1", "SAA2",
                         "AKR1C1", "AKR1C2", "BPIFA1", "CEACAM5", "ERN2",
                         "FCGBP", "GSR", "LTF", "CCNA1", "ICAM1", "ITGB1")
endothelial_features <- c("APLN", "CA4", "HEY1", "BMPR2", "CD34", "EPAS1",
                          "FCN3", "GNG11", "PECAM1", "APLNR", "COL15A1",
                          "PLVAP", "ACKR1", "POSTN", "CLDN5", "RAMP2", "ZEB1",
                          "HAS1", "KDR", "CDKN2A")
immune_features <- c("PPARG", "BANK1", "CD19", "CD79A", "LTB", "MS4A1",
                     "TNFRSF13C", "CD86", "GZMB", "HLA-DRA", "CCR7", "CXCR4",
                     "PTPRC", "TCL1A", "CD69", "CD4", "CD8A", "CD8B", "CD2",
                     "CD28", "CD3D", "CD3E", "CD3G", "FOXP3", "GZMK", "TRAC",
                     "ITM2C", "CD27", "CCL5", "LCK", "FABP4", "MARCO", "MCEMP1",
                     "SPP1", "FCN1", "S100A12", "S100A8","S100A9", "CCL22",
                     "ITGAM", "NFKB1",  "IFIT2", "FGFBP2", "GNLY", "KLRB1",
                     "KLRC1", "NKG7", "LILRA4", "BCL2", "CD79B", "CXCR5", 
                     "CXCL9", "GPR183", "HLA-DQA1", "KLRG1", "BCL2L11", "CD52", 
                     "SLC1A3", "TNFRSF9", "CTLA4",  "IL2RA", "LAG3", "PDCD1",
                     "PDIA6", "PIM2", "IL7R", "LEF1", "FASLG", "HAVCR2",
                     "ISG20", "CPA3","KIT", "TPSAB1", "C1QC", "CD68", "MS4A7",
                     "AIF1", "CD14", "FCGR3A", "FCER1G", "SLC25A37", "CD247",
                     "GZMA", "IRF7")
mesenchymal_features <- c("MFAP5", "PI16", "SFRP2", "ELN", "FAP", "AXL", "LGR6", 
                          "COL1A1", "COL1A2", "COL3A1", "DCN", "FN1", "HAS2", 
                          "LUM", "MEG3", "SPARCL1", "CTHRC1")
```


### Import data

```{r}

seurat_object <- readRDS("/tgen_labs/banovich/IPF/Spatial_ASE/ILD_ASE_Xenium_processed.rds")
DefaultAssay(seurat_object)

# Checking the number of PCs to include in the neighborhood/UMAP
features <- rownames(seurat_object)
features <- features[-grep("-", features)]
VariableFeatures(seurat_object) <- features

seurat_object <- ScaleData(seurat_object)
seurat_object <- RunPCA(seurat_object,
                        reduction.name = "pca",
                        verbose = T)
pcs <- get_pcs(seurat_object, reduction_name = "pca")
pcs

```

### DimPlots

```{r}

DimPlot(seurat_object,
        group.by = "leiden_res0.5",
        cols = cluster_col,
        #split.by = "sample",
        #ncol = 5,
        reduction = "umap",
        raster = T,
        label = T) +
  coord_fixed(ratio = 1) +
  NoLegend() +
  theme_minimal()

```

### Feature expression

```{r, fig.height=12}

DotPlot(seurat_object,
        features = unique(c(epithelial_features,
                            immune_features,
                            endothelial_features,
                            mesenchymal_features)),
        group.by = "leiden_res0.5",
        cols = c("azure", "tomato3")) +
  coord_flip() +
  theme_minimal()

```
