---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Analyzing Xenium data for allelic bias

### SNP selection

100bp probes were designed to tag exonic (or intronic) SNPs that are in high 
LD (R^2^ >0.8) with *cis*-eSNPs from [Natri & Azodi et al. 2023](https://pubmed.ncbi.nlm.nih.gov/36993211/).

Information on eQTL and tag-SNPs can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1f7HtQC07PWa1ij9UxTmgrEMX2OnHDVcrpn7Oa_VNIms/edit?usp=sharing).

### Processing and analysis

1. [Xenium data pre-processing](Xenium_preprocessing.html)\
2. [Dimensionality reduction and neighborhood graph construction](/code/clustering.py)\
3. [Post-clustering visualization and analysis](post_clustering.html)\
4. [Lineage level annotation](celltype_annotations.html)
5. [Immune cell type annotation](immune_annotations.html)
6. [Epithelial cell type annotation](epithelial_annotations.html)
7. [Endothelial and mesenchymal cell type annotation](endo_mesen_annotations.html)
8. [Post-annotation visualization and comparative analysis](post_annotation_visualization.html)
9. [Quantifying allelic imbalance](ASE.html)
10. [Visualizing the ASE results](visualize_ASE.html)
11. [Sample-level pseudobulk](samplelevel_pseudobulk.html)
12. [ASE and non-ASE probe readcount correlation](ase_readcounts.html)
13. [Plotting ASE in the spatial context](plot_spatial_exp.html)

### To do

Lineage-level pseudobulk.

### Contact

Heini Natri, hnatri@tgen.org
